-- Update the initialize_tournament_bracket function to NOT auto-generate brackets
-- Brackets are now generated by the scheduled generate_tournament_brackets function
CREATE OR REPLACE FUNCTION initialize_tournament_bracket()
RETURNS TRIGGER
LANGUAGE plpgsql
SECURITY DEFINER
AS $$
BEGIN
  -- This trigger is now only used for manual bracket generation or legacy support
  -- The main bracket generation happens via generate_tournament_brackets() scheduled function
  
  -- Only run if explicitly triggered and bracket not yet generated
  IF NEW.status = 'active' AND OLD.status = 'open' AND NEW.bracket_generated = false THEN
    -- Call the bracket generation for this specific tournament
    PERFORM generate_tournament_brackets();
  END IF;
  
  RETURN NEW;
END;
$$;
